### ISSUE TITLE
Error Code: M7702-1003

### ISSUE THREAD

**Issue by robertoviola** [gort818/qtwebflix#26]
Hi,

I compiled **Qt5.11/Qtwebengine** with enabled proprietary codec.

I followed all the instructions for building and executing the application, but when I try to play a video in Netflix I got **Error Code: M7702-1003** and the description says that WidevineCDM is missing or not updated.

I downloaded the Widevine plugin through the script and passed it when launching the application, but it still does not work.

Can you give me some advices? Why does it not work?

Best regards,
Roberto

**Comment by gort818** [comment]
Hi,

Sure, would be glad to help.

1.  What Distro are you using and what version? 
2.  Did you build qtwebflix from source?
3.  Do you have chromium installed?

**Comment by robertoviola** [comment]
I am using Ubuntu 16.04 LTS.
I built it from source.
I do not have Chromium, but I have Google Chrome 67. By the way, I also installed the Widevine plugin through the script, but qtwebflix does not work neither with the Chrome one nor with the one installed through the script.

**Comment by gort818** [comment]
Ok, so that script was meant for ubuntu 17+ beacuse qtwebengine is in the repos and it is a bit behind I think it is still qt version 5.9 or 5.10.

Since you have qt 5.11 I think we are going to need the newer widevine libs. I can write up  a script later if need be, but if you want to test it now use this.

https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_66.0.3359.181-1_amd64.deb
and extract the widevine libs

Let me know how that goes and if you need help let me know.

**Comment by robertoviola** [comment]
Hi,
Now it correctly works.
Does Google change something (some updates) in Widevine plugin for Chrome 67?
In order to work with future version of Widevine, do you think that Qt should fix this problem? Does the problem depend on Qt or this particular code?

**Comment by gort818** [comment]
So it seems everytime there is a major chromium release we need the newer widevine libs, I have been montoring and updating them accordingly.

Everytime there is a major Qt release they update  chromium  in qtwebengine and depends on a newer widevine.

The shell script I had there was intended for Ubuntu 17 & 18 since they are behind on QT release versions.

I might have to do a check and see what version of QT is installed and download the correct widevine libs.

Hope that answers your question.. and if you have any issues please let me know!

**Comment by robertoviola** [comment]
I  understood. Thank you for your help!
